# Generated by Django 3.2.8 on 2022-03-07 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0002_tb_tb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TB_tb',
            new_name='category_tb',
        ),
    ]
