# Generated by Django 3.2.8 on 2022-03-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sellerregister_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('proofupload', models.FileField(max_length=20, upload_to='')),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
