# Generated by Django 3.2.8 on 2022-03-03 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerregister_tb',
            old_name='user',
            new_name='username',
        ),
    ]
