# Generated by Django 3.2.8 on 2022-03-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_seller', '0002_rename_user_sellerregister_tb_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerregister_tb',
            name='proofupload',
            field=models.FileField(upload_to=''),
        ),
    ]
