# Generated by Django 3.2.8 on 2022-03-08 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0003_rename_tb_tb_category_tb'),
        ('site_seller', '0003_alter_sellerregister_tb_proofupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=20)),
                ('file', models.FileField(max_length=20, upload_to='')),
                ('price', models.IntegerField(max_length=20)),
                ('details', models.CharField(max_length=20)),
                ('stock', models.IntegerField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.category_tb')),
                ('sellerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_seller.sellerregister_tb')),
            ],
        ),
    ]
