# Generated by Django 3.2.8 on 2022-03-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_seller', '0004_product_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_tb',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='product_tb',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_tb',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
